// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAnswer = `-- name: CreateAnswer :exec
INSERT INTO answers (question_id, room_id, answer)
VALUES ($1, $2, $3)
`

type CreateAnswerParams struct {
	QuestionID int32
	RoomID     uuid.UUID
	Answer     string
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createAnswer, arg.QuestionID, arg.RoomID, arg.Answer)
	return err
}

const deleteAnswerByQuestionAndRoomID = `-- name: DeleteAnswerByQuestionAndRoomID :exec
DELETE FROM answers WHERE question_id = $1 AND room_id = $2
`

type DeleteAnswerByQuestionAndRoomIDParams struct {
	QuestionID int32
	RoomID     uuid.UUID
}

func (q *Queries) DeleteAnswerByQuestionAndRoomID(ctx context.Context, arg DeleteAnswerByQuestionAndRoomIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnswerByQuestionAndRoomID, arg.QuestionID, arg.RoomID)
	return err
}

const getAnswerByQuestionAndRoomID = `-- name: GetAnswerByQuestionAndRoomID :one
SELECT question_id, room_id, answer, created_at, updated_at FROM answers WHERE question_id = $1 AND room_id = $2
`

type GetAnswerByQuestionAndRoomIDParams struct {
	QuestionID int32
	RoomID     uuid.UUID
}

func (q *Queries) GetAnswerByQuestionAndRoomID(ctx context.Context, arg GetAnswerByQuestionAndRoomIDParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, getAnswerByQuestionAndRoomID, arg.QuestionID, arg.RoomID)
	var i Answer
	err := row.Scan(
		&i.QuestionID,
		&i.RoomID,
		&i.Answer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnswersByRoomID = `-- name: ListAnswersByRoomID :many
SELECT question_id, room_id, answer, created_at, updated_at FROM answers WHERE room_id = $1
`

func (q *Queries) ListAnswersByRoomID(ctx context.Context, roomID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.QuestionID,
			&i.RoomID,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnswerByQuestionAndRoomID = `-- name: UpdateAnswerByQuestionAndRoomID :one
UPDATE answers
SET answer = $3, updated_at = CURRENT_TIMESTAMP
WHERE question_id = $1 AND room_id = $2
RETURNING question_id, room_id, answer, created_at, updated_at
`

type UpdateAnswerByQuestionAndRoomIDParams struct {
	QuestionID int32
	RoomID     uuid.UUID
	Answer     string
}

func (q *Queries) UpdateAnswerByQuestionAndRoomID(ctx context.Context, arg UpdateAnswerByQuestionAndRoomIDParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, updateAnswerByQuestionAndRoomID, arg.QuestionID, arg.RoomID, arg.Answer)
	var i Answer
	err := row.Scan(
		&i.QuestionID,
		&i.RoomID,
		&i.Answer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
