// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCode = `-- name: CreateCode :one
INSERT INTO code_snippets (name, question_id, code, language)
VALUES ($1, $2, $3, $4)
RETURNING name, question_id, code, language, created_at, updated_at
`

type CreateCodeParams struct {
	Name       string
	QuestionID uuid.UUID
	Code       string
	Language   Language
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) (CodeSnippet, error) {
	row := q.db.QueryRowContext(ctx, createCode,
		arg.Name,
		arg.QuestionID,
		arg.Code,
		arg.Language,
	)
	var i CodeSnippet
	err := row.Scan(
		&i.Name,
		&i.QuestionID,
		&i.Code,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCode = `-- name: DeleteCode :exec
DELETE FROM code_snippets WHERE name = $1 AND question_id = $2
`

type DeleteCodeParams struct {
	Name       string
	QuestionID uuid.UUID
}

func (q *Queries) DeleteCode(ctx context.Context, arg DeleteCodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteCode, arg.Name, arg.QuestionID)
	return err
}

const getCode = `-- name: GetCode :one
SELECT name, question_id, code, language, created_at, updated_at FROM code_snippets WHERE name = $1 AND question_id = $2
`

type GetCodeParams struct {
	Name       string
	QuestionID uuid.UUID
}

func (q *Queries) GetCode(ctx context.Context, arg GetCodeParams) (CodeSnippet, error) {
	row := q.db.QueryRowContext(ctx, getCode, arg.Name, arg.QuestionID)
	var i CodeSnippet
	err := row.Scan(
		&i.Name,
		&i.QuestionID,
		&i.Code,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCodes = `-- name: ListCodes :many
SELECT name, question_id, code, language, created_at, updated_at FROM code_snippets WHERE question_id = $1
`

func (q *Queries) ListCodes(ctx context.Context, questionID uuid.UUID) ([]CodeSnippet, error) {
	rows, err := q.db.QueryContext(ctx, listCodes, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeSnippet
	for rows.Next() {
		var i CodeSnippet
		if err := rows.Scan(
			&i.Name,
			&i.QuestionID,
			&i.Code,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCode = `-- name: UpdateCode :one
UPDATE code_snippets
SET code = $3, updated_at = CURRENT_TIMESTAMP
WHERE name = $1 AND question_id = $2
RETURNING name, question_id, code, language, created_at, updated_at
`

type UpdateCodeParams struct {
	Name       string
	QuestionID uuid.UUID
	Code       string
}

func (q *Queries) UpdateCode(ctx context.Context, arg UpdateCodeParams) (CodeSnippet, error) {
	row := q.db.QueryRowContext(ctx, updateCode, arg.Name, arg.QuestionID, arg.Code)
	var i CodeSnippet
	err := row.Scan(
		&i.Name,
		&i.QuestionID,
		&i.Code,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
