// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCode = `-- name: CreateCode :exec
INSERT INTO code_snippets (name, question_id, room_id, code, language)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name, question_id, room_id)
DO UPDATE SET
    code = $4,
    updated_at = CURRENT_TIMESTAMP
`

type CreateCodeParams struct {
	Name       string    `json:"name"`
	QuestionID int32     `json:"question_id"`
	RoomID     uuid.UUID `json:"room_id"`
	Code       string    `json:"code"`
	Language   Language  `json:"language"`
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) error {
	_, err := q.db.ExecContext(ctx, createCode,
		arg.Name,
		arg.QuestionID,
		arg.RoomID,
		arg.Code,
		arg.Language,
	)
	return err
}

const deleteCode = `-- name: DeleteCode :exec
DELETE FROM code_snippets WHERE name = $1 AND question_id = $2
`

type DeleteCodeParams struct {
	Name       string `json:"name"`
	QuestionID int32  `json:"question_id"`
}

func (q *Queries) DeleteCode(ctx context.Context, arg DeleteCodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteCode, arg.Name, arg.QuestionID)
	return err
}

const getCodeByQuestionAndRoomIDAndName = `-- name: GetCodeByQuestionAndRoomIDAndName :one
SELECT name, question_id, room_id, code, language, created_at, updated_at FROM code_snippets WHERE question_id = $1 AND room_id = $2 AND name = $3
`

type GetCodeByQuestionAndRoomIDAndNameParams struct {
	QuestionID int32     `json:"question_id"`
	RoomID     uuid.UUID `json:"room_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetCodeByQuestionAndRoomIDAndName(ctx context.Context, arg GetCodeByQuestionAndRoomIDAndNameParams) (CodeSnippet, error) {
	row := q.db.QueryRowContext(ctx, getCodeByQuestionAndRoomIDAndName, arg.QuestionID, arg.RoomID, arg.Name)
	var i CodeSnippet
	err := row.Scan(
		&i.Name,
		&i.QuestionID,
		&i.RoomID,
		&i.Code,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCodes = `-- name: ListCodes :many
SELECT name, question_id, room_id, code, language, created_at, updated_at FROM code_snippets WHERE question_id = $1
`

func (q *Queries) ListCodes(ctx context.Context, questionID int32) ([]CodeSnippet, error) {
	rows, err := q.db.QueryContext(ctx, listCodes, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeSnippet
	for rows.Next() {
		var i CodeSnippet
		if err := rows.Scan(
			&i.Name,
			&i.QuestionID,
			&i.RoomID,
			&i.Code,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCode = `-- name: UpdateCode :one
UPDATE code_snippets
SET code = $3, updated_at = CURRENT_TIMESTAMP
WHERE name = $1 AND question_id = $2 AND room_id = $3
RETURNING name, question_id, room_id, code, language, created_at, updated_at
`

type UpdateCodeParams struct {
	Name       string `json:"name"`
	QuestionID int32  `json:"question_id"`
	Code       string `json:"code"`
}

func (q *Queries) UpdateCode(ctx context.Context, arg UpdateCodeParams) (CodeSnippet, error) {
	row := q.db.QueryRowContext(ctx, updateCode, arg.Name, arg.QuestionID, arg.Code)
	var i CodeSnippet
	err := row.Scan(
		&i.Name,
		&i.QuestionID,
		&i.RoomID,
		&i.Code,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
