// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGithubOauth = `-- name: CreateGithubOauth :exec
INSERT INTO github_oauth (
    user_id,
    github_id
) VALUES ($1, $2)
`

type CreateGithubOauthParams struct {
	UserID   uuid.UUID
	GithubID int32
}

func (q *Queries) CreateGithubOauth(ctx context.Context, arg CreateGithubOauthParams) error {
	_, err := q.db.ExecContext(ctx, createGithubOauth, arg.UserID, arg.GithubID)
	return err
}

const getGithubOauthByGithubId = `-- name: GetGithubOauthByGithubId :one
SELECT github_id, user_id, created_at, updated_at FROM github_oauth WHERE github_id = $1
`

func (q *Queries) GetGithubOauthByGithubId(ctx context.Context, githubID int32) (GithubOauth, error) {
	row := q.db.QueryRowContext(ctx, getGithubOauthByGithubId, githubID)
	var i GithubOauth
	err := row.Scan(
		&i.GithubID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubOauthByUserId = `-- name: GetGithubOauthByUserId :one
SELECT github_id, user_id, created_at, updated_at FROM github_oauth WHERE user_id = $1
`

func (q *Queries) GetGithubOauthByUserId(ctx context.Context, userID uuid.UUID) (GithubOauth, error) {
	row := q.db.QueryRowContext(ctx, getGithubOauthByUserId, userID)
	var i GithubOauth
	err := row.Scan(
		&i.GithubID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
