// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AuthType string

const (
	AuthTypeEmail  AuthType = "email"
	AuthTypeGithub AuthType = "github"
	AuthTypeNone   AuthType = "none"
)

func (e *AuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthType(s)
	case string:
		*e = AuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthType: %T", src)
	}
	return nil
}

type NullAuthType struct {
	AuthType AuthType
	Valid    bool // Valid is true if AuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthType), nil
}

type Language string

const (
	LanguagePython     Language = "python"
	LanguageJavascript Language = "javascript"
	LanguageGo         Language = "go"
)

func (e *Language) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Language(s)
	case string:
		*e = Language(s)
	default:
		return fmt.Errorf("unsupported scan type for Language: %T", src)
	}
	return nil
}

type NullLanguage struct {
	Language Language
	Valid    bool // Valid is true if Language is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.Language, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Language.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Language), nil
}

type Answer struct {
	QuestionID int32
	RoomID     uuid.UUID
	Answer     string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type CodeSnippet struct {
	Name       string
	QuestionID int32
	RoomID     uuid.UUID
	Code       string
	Language   Language
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type GithubOauth struct {
	GithubID  int32
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Question struct {
	ID          int32
	RoomID      uuid.UUID
	Done        bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Title       string
	Description string
	IsCode      bool
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type Room struct {
	ID            uuid.UUID
	Name          string
	Description   string
	OwnerID       uuid.UUID
	StartTime     time.Time
	IsActive      bool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	ParticipantID uuid.NullUUID
}

type User struct {
	ID                uuid.UUID
	Email             string
	Name              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Password          sql.NullString
	Pending           sql.NullBool
	ProfilePictureUrl string
	Auth              AuthType
}

type VerificationLink struct {
	UserID    uuid.UUID
	Code      string
	ExpiresAt time.Time
}
