// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Language string

const (
	LanguagePython     Language = "python"
	LanguageJavascript Language = "javascript"
	LanguageGo         Language = "go"
)

func (e *Language) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Language(s)
	case string:
		*e = Language(s)
	default:
		return fmt.Errorf("unsupported scan type for Language: %T", src)
	}
	return nil
}

type NullLanguage struct {
	Language Language
	Valid    bool // Valid is true if Language is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.Language, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Language.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Language), nil
}

type OauthProvider string

const (
	OauthProviderGithub OauthProvider = "github"
	OauthProviderGoogle OauthProvider = "google"
	OauthProviderEmail  OauthProvider = "email"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider
	Valid         bool // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type Answer struct {
	QuestionID int32
	RoomID     uuid.UUID
	Answer     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CodeSnippet struct {
	Name       string
	QuestionID int32
	RoomID     uuid.UUID
	Code       string
	Language   Language
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Oauth struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Provider   OauthProvider
	ProviderID sql.NullString
	Email      string
	Password   sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Question struct {
	ID          int32
	RoomID      uuid.UUID
	Done        bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	IsCode      bool
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type Room struct {
	ID            uuid.UUID
	Name          string
	Description   string
	OwnerID       uuid.UUID
	StartTime     time.Time
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ParticipantID uuid.NullUUID
}

type User struct {
	ID                uuid.UUID
	Email             string
	Name              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProfilePictureUrl string
	Verified          bool
}

type VerificationLink struct {
	UserID    uuid.UUID
	Code      string
	ExpiresAt time.Time
	CreatedAt time.Time
}
