// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Language string

const (
	LanguagePython     Language = "python"
	LanguageJavascript Language = "javascript"
	LanguageGo         Language = "go"
)

func (e *Language) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Language(s)
	case string:
		*e = Language(s)
	default:
		return fmt.Errorf("unsupported scan type for Language: %T", src)
	}
	return nil
}

type NullLanguage struct {
	Language Language `json:"language"`
	Valid    bool     `json:"valid"` // Valid is true if Language is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.Language, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Language.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Language), nil
}

type OauthProvider string

const (
	OauthProviderGithub OauthProvider = "github"
	OauthProviderGoogle OauthProvider = "google"
	OauthProviderEmail  OauthProvider = "email"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider `json:"oauth_provider"`
	Valid         bool          `json:"valid"` // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type RoomStatus string

const (
	RoomStatusPending   RoomStatus = "pending"
	RoomStatusLive      RoomStatus = "live"
	RoomStatusReviewing RoomStatus = "reviewing"
	RoomStatusCompleted RoomStatus = "completed"
	RoomStatusCancelled RoomStatus = "cancelled"
)

func (e *RoomStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoomStatus(s)
	case string:
		*e = RoomStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RoomStatus: %T", src)
	}
	return nil
}

type NullRoomStatus struct {
	RoomStatus RoomStatus `json:"room_status"`
	Valid      bool       `json:"valid"` // Valid is true if RoomStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoomStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RoomStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoomStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoomStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoomStatus), nil
}

type Answer struct {
	QuestionID int32     `json:"question_id"`
	RoomID     uuid.UUID `json:"room_id"`
	Answer     string    `json:"answer"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CodeSnippet struct {
	Name       string    `json:"name"`
	QuestionID int32     `json:"question_id"`
	RoomID     uuid.UUID `json:"room_id"`
	Code       string    `json:"code"`
	Language   Language  `json:"language"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Oauth struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Provider   OauthProvider  `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	Email      string         `json:"email"`
	Password   sql.NullString `json:"password"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Question struct {
	ID          int32        `json:"id"`
	RoomID      uuid.UUID    `json:"room_id"`
	Done        bool         `json:"done"`
	Passed      sql.NullBool `json:"passed"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	IsCode      bool         `json:"is_code"`
}

type RefreshToken struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Room struct {
	ID            uuid.UUID     `json:"id"`
	Description   string        `json:"description"`
	OwnerID       uuid.UUID     `json:"owner_id"`
	StartTime     time.Time     `json:"start_time"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	ParticipantID uuid.NullUUID `json:"participant_id"`
	Role          string        `json:"role"`
	Company       string        `json:"company"`
	StartedAt     sql.NullTime  `json:"started_at"`
	EndedAt       sql.NullTime  `json:"ended_at"`
	Status        RoomStatus    `json:"status"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Email             string    `json:"email"`
	Name              string    `json:"name"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	ProfilePictureUrl string    `json:"profile_picture_url"`
	Verified          bool      `json:"verified"`
}

type VerificationLink struct {
	UserID    uuid.UUID `json:"user_id"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}
