// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEmailOauth = `-- name: CreateEmailOauth :exec
INSERT INTO oauth (
    provider,
    user_id,
    email,
    password
) VALUES ('email', $1, $2, $3)
`

type CreateEmailOauthParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	Email    string         `json:"email"`
	Password sql.NullString `json:"password"`
}

func (q *Queries) CreateEmailOauth(ctx context.Context, arg CreateEmailOauthParams) error {
	_, err := q.db.ExecContext(ctx, createEmailOauth, arg.UserID, arg.Email, arg.Password)
	return err
}

const createGithubOauth = `-- name: CreateGithubOauth :exec
INSERT INTO oauth (
    provider,
    user_id,
    provider_id,
    email
) VALUES ('github', $1, $2, $3)
`

type CreateGithubOauthParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	ProviderID sql.NullString `json:"provider_id"`
	Email      string         `json:"email"`
}

func (q *Queries) CreateGithubOauth(ctx context.Context, arg CreateGithubOauthParams) error {
	_, err := q.db.ExecContext(ctx, createGithubOauth, arg.UserID, arg.ProviderID, arg.Email)
	return err
}

const createGoogleOauth = `-- name: CreateGoogleOauth :exec
INSERT INTO oauth (
    provider,
    user_id,
    provider_id,
    email
) VALUES ('google', $1, $2, $3)
`

type CreateGoogleOauthParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	ProviderID sql.NullString `json:"provider_id"`
	Email      string         `json:"email"`
}

func (q *Queries) CreateGoogleOauth(ctx context.Context, arg CreateGoogleOauthParams) error {
	_, err := q.db.ExecContext(ctx, createGoogleOauth, arg.UserID, arg.ProviderID, arg.Email)
	return err
}

const deleteOauthByUserIdAndProvider = `-- name: DeleteOauthByUserIdAndProvider :exec
DELETE FROM oauth WHERE user_id = $1 AND provider = $2
`

type DeleteOauthByUserIdAndProviderParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	Provider OauthProvider `json:"provider"`
}

func (q *Queries) DeleteOauthByUserIdAndProvider(ctx context.Context, arg DeleteOauthByUserIdAndProviderParams) error {
	_, err := q.db.ExecContext(ctx, deleteOauthByUserIdAndProvider, arg.UserID, arg.Provider)
	return err
}

const getOauthByEmailAndProvider = `-- name: GetOauthByEmailAndProvider :one
SELECT id, user_id, provider, provider_id, email, password, created_at, updated_at FROM oauth WHERE email = $1 AND provider = $2
`

type GetOauthByEmailAndProviderParams struct {
	Email    string        `json:"email"`
	Provider OauthProvider `json:"provider"`
}

func (q *Queries) GetOauthByEmailAndProvider(ctx context.Context, arg GetOauthByEmailAndProviderParams) (Oauth, error) {
	row := q.db.QueryRowContext(ctx, getOauthByEmailAndProvider, arg.Email, arg.Provider)
	var i Oauth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOauthByUserIdAndProvider = `-- name: GetOauthByUserIdAndProvider :one
SELECT id, user_id, provider, provider_id, email, password, created_at, updated_at FROM oauth WHERE user_id = $1 AND provider = $2
`

type GetOauthByUserIdAndProviderParams struct {
	UserID   uuid.UUID     `json:"user_id"`
	Provider OauthProvider `json:"provider"`
}

func (q *Queries) GetOauthByUserIdAndProvider(ctx context.Context, arg GetOauthByUserIdAndProviderParams) (Oauth, error) {
	row := q.db.QueryRowContext(ctx, getOauthByUserIdAndProvider, arg.UserID, arg.Provider)
	var i Oauth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOauthEmailByProviderId = `-- name: GetOauthEmailByProviderId :one
SELECT email FROM oauth WHERE provider = $1 AND provider_id = $2
`

type GetOauthEmailByProviderIdParams struct {
	Provider   OauthProvider  `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
}

func (q *Queries) GetOauthEmailByProviderId(ctx context.Context, arg GetOauthEmailByProviderIdParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOauthEmailByProviderId, arg.Provider, arg.ProviderID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getOauthProvidersByUserId = `-- name: GetOauthProvidersByUserId :many
SELECT provider, provider_id, email FROM oauth WHERE user_id = $1
`

type GetOauthProvidersByUserIdRow struct {
	Provider   OauthProvider  `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
	Email      string         `json:"email"`
}

func (q *Queries) GetOauthProvidersByUserId(ctx context.Context, userID uuid.UUID) ([]GetOauthProvidersByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getOauthProvidersByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOauthProvidersByUserIdRow
	for rows.Next() {
		var i GetOauthProvidersByUserIdRow
		if err := rows.Scan(&i.Provider, &i.ProviderID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByProviderId = `-- name: GetUserByProviderId :one
SELECT u.id as userID, u.name as userName, u.email as userEmail
FROM users u
JOIN oauth o ON u.id = o.user_id
WHERE o.provider = $1 AND o.provider_id = $2 AND u.verified = TRUE
`

type GetUserByProviderIdParams struct {
	Provider   OauthProvider  `json:"provider"`
	ProviderID sql.NullString `json:"provider_id"`
}

type GetUserByProviderIdRow struct {
	Userid    uuid.UUID `json:"userid"`
	Username  string    `json:"username"`
	Useremail string    `json:"useremail"`
}

func (q *Queries) GetUserByProviderId(ctx context.Context, arg GetUserByProviderIdParams) (GetUserByProviderIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderId, arg.Provider, arg.ProviderID)
	var i GetUserByProviderIdRow
	err := row.Scan(&i.Userid, &i.Username, &i.Useremail)
	return i, err
}

const updateOauthPassword = `-- name: UpdateOauthPassword :exec
UPDATE oauth SET password = $1, updated_at = CURRENT_TIMESTAMP WHERE user_id = $2 AND provider = 'email'
`

type UpdateOauthPasswordParams struct {
	Password sql.NullString `json:"password"`
	UserID   uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateOauthPassword(ctx context.Context, arg UpdateOauthPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateOauthPassword, arg.Password, arg.UserID)
	return err
}
