// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO question (room_id, question) VALUES ($1, $2)
`

type CreateQuestionParams struct {
	RoomID   uuid.UUID
	Question string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createQuestion, arg.RoomID, arg.Question)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM question WHERE id = $1 AND room_id = $2
`

type DeleteQuestionParams struct {
	ID     int32
	RoomID uuid.UUID
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, arg.ID, arg.RoomID)
	return err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, room_id, question, done, passed, created_at, updated_at FROM question WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id int32) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Question,
		&i.Done,
		&i.Passed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionsByRoomID = `-- name: GetQuestionsByRoomID :many
SELECT id, room_id, question, done, passed, created_at, updated_at FROM question WHERE room_id = $1
`

func (q *Queries) GetQuestionsByRoomID(ctx context.Context, roomID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Question,
			&i.Done,
			&i.Passed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, room_id, question, done, passed, created_at, updated_at FROM question
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Question,
			&i.Done,
			&i.Passed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :exec
UPDATE question SET question = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
`

type UpdateQuestionParams struct {
	Question string
	ID       int32
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestion, arg.Question, arg.ID)
	return err
}
