// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO questions (room_id, title, description, is_code) VALUES ($1, $2, $3, $4)
`

type CreateQuestionParams struct {
	RoomID      uuid.UUID
	Title       string
	Description string
	IsCode      bool
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createQuestion,
		arg.RoomID,
		arg.Title,
		arg.Description,
		arg.IsCode,
	)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1 AND room_id = $2
`

type DeleteQuestionParams struct {
	ID     int32
	RoomID uuid.UUID
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, arg.ID, arg.RoomID)
	return err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, room_id, done, created_at, updated_at, answer, title, description, is_code FROM questions WHERE id = $1 AND room_id = $2
`

type GetQuestionByIDParams struct {
	ID     int32
	RoomID uuid.UUID
}

func (q *Queries) GetQuestionByID(ctx context.Context, arg GetQuestionByIDParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, arg.ID, arg.RoomID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Answer,
		&i.Title,
		&i.Description,
		&i.IsCode,
	)
	return i, err
}

const getQuestionsByRoomID = `-- name: GetQuestionsByRoomID :many
SELECT id, room_id, done, created_at, updated_at, answer, title, description, is_code FROM questions WHERE room_id = $1
`

func (q *Queries) GetQuestionsByRoomID(ctx context.Context, roomID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Answer,
			&i.Title,
			&i.Description,
			&i.IsCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, room_id, done, created_at, updated_at, answer, title, description, is_code FROM questions WHERE room_id = $1
`

func (q *Queries) ListQuestions(ctx context.Context, roomID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Answer,
			&i.Title,
			&i.Description,
			&i.IsCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :exec
UPDATE questions SET title = $1, description = $2, is_code = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $4 AND room_id = $5
`

type UpdateQuestionParams struct {
	Title       string
	Description string
	IsCode      bool
	ID          int32
	RoomID      uuid.UUID
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestion,
		arg.Title,
		arg.Description,
		arg.IsCode,
		arg.ID,
		arg.RoomID,
	)
	return err
}
