// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (token, user_id, expires_at) VALUES ($1, $2, $3)
` //#nosec G101 -- sqlc generated SQL, not a hardcoded credential

type CreateRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_token WHERE token = $1
` //#nosec G101 -- sqlc generated SQL, not a hardcoded credential

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}

const deleteRefreshTokenByUserId = `-- name: DeleteRefreshTokenByUserId :exec
DELETE FROM refresh_token WHERE user_id = $1
` //#nosec G101 -- sqlc generated SQL, not a hardcoded credential

func (q *Queries) DeleteRefreshTokenByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenByUserId, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token, user_id, expires_at FROM refresh_token WHERE token = $1
` //#nosec G101 -- sqlc generated SQL, not a hardcoded credential

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}
