// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addParticipantToRoom = `-- name: AddParticipantToRoom :exec
UPDATE room SET participant_id = $2 WHERE id = $1 AND status = 'pending'
`

type AddParticipantToRoomParams struct {
	ID            uuid.UUID     `json:"id"`
	ParticipantID uuid.NullUUID `json:"participant_id"`
}

func (q *Queries) AddParticipantToRoom(ctx context.Context, arg AddParticipantToRoomParams) error {
	_, err := q.db.ExecContext(ctx, addParticipantToRoom, arg.ID, arg.ParticipantID)
	return err
}

const cancelRoom = `-- name: CancelRoom :exec
UPDATE room SET status = 'cancelled', updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND status = 'pending' AND owner_id = $2
`

type CancelRoomParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CancelRoom(ctx context.Context, arg CancelRoomParams) error {
	_, err := q.db.ExecContext(ctx, cancelRoom, arg.ID, arg.OwnerID)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO room (role, company, description, owner_id, start_time) VALUES ($1, $2, $3, $4, $5)
`

type CreateRoomParams struct {
	Role        string    `json:"role"`
	Company     string    `json:"company"`
	Description string    `json:"description"`
	OwnerID     uuid.UUID `json:"owner_id"`
	StartTime   time.Time `json:"start_time"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom,
		arg.Role,
		arg.Company,
		arg.Description,
		arg.OwnerID,
		arg.StartTime,
	)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM room WHERE id = $1 AND owner_id = $2 AND status = 'pending'
`

type DeleteRoomParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, arg.ID, arg.OwnerID)
	return err
}

const endRoom = `-- name: EndRoom :exec
UPDATE room SET status = 'reviewing', ended_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND status = 'live' AND owner_id = $2
`

type EndRoomParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) EndRoom(ctx context.Context, arg EndRoomParams) error {
	_, err := q.db.ExecContext(ctx, endRoom, arg.ID, arg.OwnerID)
	return err
}

const getPassRate = `-- name: GetPassRate :one
SELECT COALESCE( ROUND( AVG( CASE WHEN passed = true THEN 1.0 ELSE 0.0 END) * 100, 2), 0.0)::float8 as pass_rate from room WHERE participant_id = $1 AND status = 'completed'
`

func (q *Queries) GetPassRate(ctx context.Context, participantID uuid.NullUUID) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPassRate, participantID)
	var pass_rate float64
	err := row.Scan(&pass_rate)
	return pass_rate, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.OwnerID,
		&i.StartTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParticipantID,
		&i.Role,
		&i.Company,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Feedback,
		&i.Passed,
	)
	return i, err
}

const getRoomCountByStatus = `-- name: GetRoomCountByStatus :one
SELECT COUNT(*) FROM room WHERE (owner_id = $1 OR participant_id = $1) AND status = ANY($2::room_status[])
`

type GetRoomCountByStatusParams struct {
	OwnerID uuid.UUID    `json:"owner_id"`
	Column2 []RoomStatus `json:"column_2"`
}

func (q *Queries) GetRoomCountByStatus(ctx context.Context, arg GetRoomCountByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRoomCountByStatus, arg.OwnerID, pq.Array(arg.Column2))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRoomsByOwnerID = `-- name: GetRoomsByOwnerID :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE owner_id = $1
`

func (q *Queries) GetRoomsByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByOwnerIDAndStatus = `-- name: GetRoomsByOwnerIDAndStatus :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE owner_id = $1 AND status = ANY($2::room_status[]) ORDER BY start_time ASC
`

type GetRoomsByOwnerIDAndStatusParams struct {
	OwnerID uuid.UUID    `json:"owner_id"`
	Column2 []RoomStatus `json:"column_2"`
}

func (q *Queries) GetRoomsByOwnerIDAndStatus(ctx context.Context, arg GetRoomsByOwnerIDAndStatusParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwnerIDAndStatus, arg.OwnerID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByOwnerIDOrParticipantID = `-- name: GetRoomsByOwnerIDOrParticipantID :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE (owner_id = $1 OR participant_id = $1) ORDER BY start_time ASC
`

func (q *Queries) GetRoomsByOwnerIDOrParticipantID(ctx context.Context, ownerID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwnerIDOrParticipantID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByOwnerIDOrParticipantIDAndStatus = `-- name: GetRoomsByOwnerIDOrParticipantIDAndStatus :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE (owner_id = $1 OR participant_id = $1) AND status = ANY($2::room_status[]) ORDER BY start_time ASC
`

type GetRoomsByOwnerIDOrParticipantIDAndStatusParams struct {
	OwnerID uuid.UUID    `json:"owner_id"`
	Column2 []RoomStatus `json:"column_2"`
}

func (q *Queries) GetRoomsByOwnerIDOrParticipantIDAndStatus(ctx context.Context, arg GetRoomsByOwnerIDOrParticipantIDAndStatusParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwnerIDOrParticipantIDAndStatus, arg.OwnerID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByParticipantID = `-- name: GetRoomsByParticipantID :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE participant_id = $1
`

func (q *Queries) GetRoomsByParticipantID(ctx context.Context, participantID uuid.NullUUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByParticipantID, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByParticipantIDAndStatus = `-- name: GetRoomsByParticipantIDAndStatus :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room WHERE participant_id = $1 AND status = ANY($2::room_status[]) ORDER BY start_time ASC
`

type GetRoomsByParticipantIDAndStatusParams struct {
	ParticipantID uuid.NullUUID `json:"participant_id"`
	Column2       []RoomStatus  `json:"column_2"`
}

func (q *Queries) GetRoomsByParticipantIDAndStatus(ctx context.Context, arg GetRoomsByParticipantIDAndStatusParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByParticipantIDAndStatus, arg.ParticipantID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, description, owner_id, start_time, created_at, updated_at, participant_id, role, company, status, started_at, ended_at, feedback, passed FROM room
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Feedback,
			&i.Passed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipantFromRoom = `-- name: RemoveParticipantFromRoom :exec
UPDATE room SET participant_id = NULL WHERE id = $1
`

func (q *Queries) RemoveParticipantFromRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeParticipantFromRoom, id)
	return err
}

const rescheduleRoom = `-- name: RescheduleRoom :exec
UPDATE room SET start_time = $2, status = 'pending', updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND owner_id = $3 AND status = 'cancelled'
`

type RescheduleRoomParams struct {
	ID        uuid.UUID `json:"id"`
	StartTime time.Time `json:"start_time"`
	OwnerID   uuid.UUID `json:"owner_id"`
}

func (q *Queries) RescheduleRoom(ctx context.Context, arg RescheduleRoomParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleRoom, arg.ID, arg.StartTime, arg.OwnerID)
	return err
}

const startRoom = `-- name: StartRoom :exec
UPDATE room SET status = 'live', started_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = $1 AND status = 'pending' AND owner_id = $2
`

type StartRoomParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) StartRoom(ctx context.Context, arg StartRoomParams) error {
	_, err := q.db.ExecContext(ctx, startRoom, arg.ID, arg.OwnerID)
	return err
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE room SET role = $1, company = $2, description = $3, start_time = $4, updated_at = CURRENT_TIMESTAMP WHERE id = $5 AND owner_id = $6 AND status = 'pending'
`

type UpdateRoomParams struct {
	Role        string    `json:"role"`
	Company     string    `json:"company"`
	Description string    `json:"description"`
	StartTime   time.Time `json:"start_time"`
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom,
		arg.Role,
		arg.Company,
		arg.Description,
		arg.StartTime,
		arg.ID,
		arg.OwnerID,
	)
	return err
}
