// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO room (id, name, description, owner_id, start_time) VALUES ($1, $2, $3, $4, $5)
`

type CreateRoomParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	OwnerID     uuid.UUID
	StartTime   time.Time
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.StartTime,
	)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM room WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, description, owner_id, start_time, is_active, created_at, updated_at, participant_id FROM room WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.StartTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParticipantID,
	)
	return i, err
}

const getRoomByName = `-- name: GetRoomByName :one
SELECT id, name, description, owner_id, start_time, is_active, created_at, updated_at, participant_id FROM room WHERE name = $1
`

func (q *Queries) GetRoomByName(ctx context.Context, name string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByName, name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.StartTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParticipantID,
	)
	return i, err
}

const getRoomsByOwnerID = `-- name: GetRoomsByOwnerID :many
SELECT id, name, description, owner_id, start_time, is_active, created_at, updated_at, participant_id FROM room WHERE owner_id = $1
`

func (q *Queries) GetRoomsByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, description, owner_id, start_time, is_active, created_at, updated_at, participant_id FROM room
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE room SET name = $1, description = $2, start_time = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $4
`

type UpdateRoomParams struct {
	Name        string
	Description string
	StartTime   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom,
		arg.Name,
		arg.Description,
		arg.StartTime,
		arg.ID,
	)
	return err
}
