// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO room (role, company, description, owner_id, start_time) VALUES ($1, $2, $3, $4, $5)
`

type CreateRoomParams struct {
	Role        string
	Company     string
	Description string
	OwnerID     uuid.UUID
	StartTime   time.Time
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom,
		arg.Role,
		arg.Company,
		arg.Description,
		arg.OwnerID,
		arg.StartTime,
	)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM room WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, description, owner_id, start_time, is_active, created_at, updated_at, participant_id, role, company FROM room WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.OwnerID,
		&i.StartTime,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParticipantID,
		&i.Role,
		&i.Company,
	)
	return i, err
}

const getRoomsByOwnerID = `-- name: GetRoomsByOwnerID :many
SELECT id, description, owner_id, start_time, is_active, created_at, updated_at, participant_id, role, company FROM room WHERE owner_id = $1
`

func (q *Queries) GetRoomsByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByParticipantID = `-- name: GetRoomsByParticipantID :many
SELECT id, description, owner_id, start_time, is_active, created_at, updated_at, participant_id, role, company FROM room WHERE participant_id = $1
`

func (q *Queries) GetRoomsByParticipantID(ctx context.Context, participantID uuid.NullUUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByParticipantID, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinRoom = `-- name: JoinRoom :exec
UPDATE room SET participant_id = $2 WHERE id = $1
`

type JoinRoomParams struct {
	ID            uuid.UUID
	ParticipantID uuid.NullUUID
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) error {
	_, err := q.db.ExecContext(ctx, joinRoom, arg.ID, arg.ParticipantID)
	return err
}

const listRooms = `-- name: ListRooms :many
SELECT id, description, owner_id, start_time, is_active, created_at, updated_at, participant_id, role, company FROM room
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.OwnerID,
			&i.StartTime,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantID,
			&i.Role,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
UPDATE room SET participant_id = NULL WHERE id = $1 AND participant_id = $2
`

type RemoveParticipantParams struct {
	ID            uuid.UUID
	ParticipantID uuid.NullUUID
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeParticipant, arg.ID, arg.ParticipantID)
	return err
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE room SET role = $1, company = $2, description = $3, start_time = $4, updated_at = CURRENT_TIMESTAMP WHERE id = $5
`

type UpdateRoomParams struct {
	Role        string
	Company     string
	Description string
	StartTime   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.ExecContext(ctx, updateRoom,
		arg.Role,
		arg.Company,
		arg.Description,
		arg.StartTime,
		arg.ID,
	)
	return err
}
