// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserWithEmailPassword = `-- name: CreateUserWithEmailPassword :exec
INSERT INTO users (id, email, password, name, created_at, updated_at) VALUES ($1, $2, $3, $4, NOW(), NOW())
`

type CreateUserWithEmailPasswordParams struct {
	ID       uuid.UUID
	Email    string
	Password sql.NullString
	Name     sql.NullString
}

func (q *Queries) CreateUserWithEmailPassword(ctx context.Context, arg CreateUserWithEmailPasswordParams) error {
	_, err := q.db.ExecContext(ctx, createUserWithEmailPassword,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Name,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, updated_at, password FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
	)
	return i, err
}
