// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserWithEmailPassword = `-- name: CreateUserWithEmailPassword :exec
INSERT INTO users (id, email, password, name, created_at, updated_at) VALUES ($1, $2, $3, $4, NOW(), NOW())
` //#nosec G101 -- sqlc generated SQL, not a hardcoded credential

type CreateUserWithEmailPasswordParams struct {
	ID       uuid.UUID
	Email    string
	Password sql.NullString
	Name     string
}

func (q *Queries) CreateUserWithEmailPassword(ctx context.Context, arg CreateUserWithEmailPasswordParams) error {
	_, err := q.db.ExecContext(ctx, createUserWithEmailPassword,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Name,
	)
	return err
}

const createUserWithGithub = `-- name: CreateUserWithGithub :exec
INSERT INTO users (id, name, email, profile_picture_url, auth, created_at, updated_at) VALUES ($1, $2, $3, $4, 'github', NOW(), NOW())
`

type CreateUserWithGithubParams struct {
	ID                uuid.UUID
	Name              string
	Email             string
	ProfilePictureUrl string
}

func (q *Queries) CreateUserWithGithub(ctx context.Context, arg CreateUserWithGithubParams) error {
	_, err := q.db.ExecContext(ctx, createUserWithGithub,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.ProfilePictureUrl,
	)
	return err
}

const getPendingStatus = `-- name: GetPendingStatus :one
SELECT pending FROM users WHERE id = $1
`

func (q *Queries) GetPendingStatus(ctx context.Context, id uuid.UUID) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, getPendingStatus, id)
	var pending sql.NullBool
	err := row.Scan(&pending)
	return pending, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, updated_at, password, pending, profile_picture_url, auth FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.Pending,
		&i.ProfilePictureUrl,
		&i.Auth,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, name, created_at, updated_at, password, pending, profile_picture_url, auth FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.Pending,
		&i.ProfilePictureUrl,
		&i.Auth,
	)
	return i, err
}

const getUsersByEmail = `-- name: GetUsersByEmail :many
SELECT id, email, name, created_at, updated_at, password, pending, profile_picture_url, auth FROM users WHERE email = $1
`

func (q *Queries) GetUsersByEmail(ctx context.Context, email string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Password,
			&i.Pending,
			&i.ProfilePictureUrl,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPendingStatus = `-- name: SetPendingStatus :exec
UPDATE users SET pending = $1 WHERE id = $2
`

type SetPendingStatusParams struct {
	Pending sql.NullBool
	ID      uuid.UUID
}

func (q *Queries) SetPendingStatus(ctx context.Context, arg SetPendingStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPendingStatus, arg.Pending, arg.ID)
	return err
}
