// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_link.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationLink = `-- name: CreateVerificationLink :exec
INSERT INTO verification_links (user_id, code, expires_at)
VALUES ($1, $2, $3)
`

type CreateVerificationLinkParams struct {
	UserID    uuid.UUID
	Code      string
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationLink(ctx context.Context, arg CreateVerificationLinkParams) error {
	_, err := q.db.ExecContext(ctx, createVerificationLink, arg.UserID, arg.Code, arg.ExpiresAt)
	return err
}

const deleteVerificationLink = `-- name: DeleteVerificationLink :exec
DELETE FROM verification_links WHERE code = $1
`

func (q *Queries) DeleteVerificationLink(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationLink, code)
	return err
}

const deleteVerificationLinksByUserId = `-- name: DeleteVerificationLinksByUserId :exec
DELETE FROM verification_links WHERE user_id = $1
`

func (q *Queries) DeleteVerificationLinksByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationLinksByUserId, userID)
	return err
}

const getVerificationLink = `-- name: GetVerificationLink :one
SELECT user_id, code, expires_at FROM verification_links WHERE code = $1
`

func (q *Queries) GetVerificationLink(ctx context.Context, code string) (VerificationLink, error) {
	row := q.db.QueryRowContext(ctx, getVerificationLink, code)
	var i VerificationLink
	err := row.Scan(&i.UserID, &i.Code, &i.ExpiresAt)
	return i, err
}
