import type { Metadata } from "next";
import { Space_Grotesk  } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";


const space_grotesk  = Space_Grotesk ({
  variable: "--space_grotesk ",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.variable} ${space_grotesk.className} antialiased`}
      >
        {children}
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
