-- +goose Up
ALTER TABLE room ADD COLUMN role VARCHAR(100) NOT NULL;
ALTER TABLE room ADD COLUMN company VARCHAR(100) NOT NULL;

ALTER TABLE room DROP COLUMN name;

-- +goose Down
ALTER TABLE room DROP COLUMN role;
ALTER TABLE room DROP COLUMN company;

ALTER TABLE room ADD COLUMN name VARCHAR(255) NOT NULL;
